using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Vectrik.Models.Enums;

namespace Vectrik.Models;

/// <summary>
/// Atomic dispatch unit — tells an operator to set up a machine with a specific program.
/// Lifecycle: Queued → Assigned → InProgress → PendingVerification → Verified → Completed.
/// Decoupled from StageExecution so dispatches can be cancelled/deferred without corrupting execution tracking.
/// </summary>
public class SetupDispatch
{
    public int Id { get; set; }

    /// <summary>Auto-generated dispatch number (e.g. "DSP-00142").</summary>
    [Required, MaxLength(50)]
    public string DispatchNumber { get; set; } = string.Empty;

    // ── Core References ──────────────────────────────────────

    public int MachineId { get; set; }

    public int? MachineProgramId { get; set; }

    public int? StageExecutionId { get; set; }

    public int? JobId { get; set; }

    /// <summary>Denormalized for fast queries — the part being set up for.</summary>
    public int? PartId { get; set; }

    // ── Status & Type ────────────────────────────────────────

    public DispatchStatus Status { get; set; } = DispatchStatus.Queued;

    public DispatchType DispatchType { get; set; } = DispatchType.Setup;

    // ── Priority ─────────────────────────────────────────────

    /// <summary>Composite priority score (1-100). Higher = more urgent.</summary>
    public int Priority { get; set; } = 50;

    /// <summary>Human-readable reason for the priority score.</summary>
    [MaxLength(500)]
    public string? PriorityReason { get; set; }

    /// <summary>JSON breakdown of scoring components for UI tooltip.</summary>
    public string? ScoreBreakdownJson { get; set; }

    // ── Assignment ───────────────────────────────────────────

    public int? AssignedOperatorId { get; set; }

    public int? RequestedByUserId { get; set; }

    // ── Time Estimates & Actuals ─────────────────────────────

    public double? EstimatedSetupMinutes { get; set; }
    public double? ActualSetupMinutes { get; set; }
    public double? EstimatedChangeoverMinutes { get; set; }
    public double? ActualChangeoverMinutes { get; set; }

    // ── Tooling & Instructions ───────────────────────────────

    [MaxLength(500)]
    public string? ToolingRequired { get; set; }

    [MaxLength(200)]
    public string? FixtureRequired { get; set; }

    public int? WorkInstructionId { get; set; }

    // ── Timestamps ───────────────────────────────────────────

    public DateTime? ScheduledStartAt { get; set; }
    public DateTime QueuedAt { get; set; } = DateTime.UtcNow;
    public DateTime? AssignedAt { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? VerifiedAt { get; set; }
    public DateTime? CompletedAt { get; set; }

    // ── Changeover Tracking ──────────────────────────────────

    /// <summary>Program the machine is changing FROM (null = fresh setup).</summary>
    public int? ChangeoverFromProgramId { get; set; }

    /// <summary>Program the machine is changing TO.</summary>
    public int? ChangeoverToProgramId { get; set; }

    // ── Chaining & Dependencies ──────────────────────────────

    /// <summary>FK to a predecessor dispatch that must complete first.</summary>
    public int? PredecessorDispatchId { get; set; }

    /// <summary>FK to MaintenanceWorkOrder if DispatchType is Maintenance.</summary>
    public int? MaintenanceWorkOrderId { get; set; }

    // ── Flags ────────────────────────────────────────────────

    /// <summary>True if generated by the auto-dispatch engine (requires approval if configured).</summary>
    public bool IsAutoGenerated { get; set; }

    [MaxLength(1000)]
    public string? Notes { get; set; }

    // ── Audit ────────────────────────────────────────────────

    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;
    public DateTime LastModifiedDate { get; set; } = DateTime.UtcNow;

    [MaxLength(100)]
    public string? CreatedBy { get; set; }

    [MaxLength(100)]
    public string? LastModifiedBy { get; set; }

    // ── Navigation ───────────────────────────────────────────

    public virtual Machine Machine { get; set; } = null!;
    public virtual MachineProgram? MachineProgram { get; set; }
    public virtual StageExecution? StageExecution { get; set; }
    public virtual Job? Job { get; set; }
    public virtual Part? Part { get; set; }
    public virtual User? AssignedOperator { get; set; }
    public virtual User? RequestedByUser { get; set; }
    public virtual WorkInstruction? WorkInstruction { get; set; }
    public virtual SetupDispatch? PredecessorDispatch { get; set; }

    // ── Computed ─────────────────────────────────────────────

    [NotMapped]
    public bool IsActive => Status is DispatchStatus.Queued or DispatchStatus.Assigned
        or DispatchStatus.InProgress or DispatchStatus.PendingVerification;

    [NotMapped]
    public bool IsChangeover => ChangeoverFromProgramId.HasValue;

    [NotMapped]
    public string StatusDisplay => Status switch
    {
        DispatchStatus.Queued => "Queued",
        DispatchStatus.Assigned => "Assigned",
        DispatchStatus.InProgress => "In Progress",
        DispatchStatus.PendingVerification => "Pending Verification",
        DispatchStatus.Verified => "Verified",
        DispatchStatus.Completed => "Completed",
        DispatchStatus.Cancelled => "Cancelled",
        DispatchStatus.Deferred => "Deferred",
        DispatchStatus.Blocked => "Blocked",
        _ => Status.ToString()
    };

    [NotMapped]
    public string TypeDisplay => DispatchType switch
    {
        DispatchType.Setup => "Setup",
        DispatchType.Changeover => "Changeover",
        DispatchType.Maintenance => "Maintenance",
        DispatchType.BuildPlateLoad => "Build Plate Load",
        DispatchType.Inspection => "Inspection",
        DispatchType.Teardown => "Teardown",
        _ => DispatchType.ToString()
    };
}
